<?php
/**
 * Loads the vendored Datastar PHP SDK.
 *
 * Generated by bin/vendor-datastar.sh. Do not edit by hand.
 * Required only from the SSE endpoint, never at boot: these files use
 * enums, which are a parse error below PHP 8.1.
 *
 * @package UltralightCarouselViaSse
 */

defined( 'ABSPATH' ) || exit;

require_once __DIR__ . '/events/EventInterface.php';
require_once __DIR__ . '/enums/EventType.php';
require_once __DIR__ . '/enums/ElementPatchMode.php';
require_once __DIR__ . '/enums/NamespaceType.php';
require_once __DIR__ . '/Consts.php';
require_once __DIR__ . '/ServerSentEventData.php';
require_once __DIR__ . '/events/EventTrait.php';
require_once __DIR__ . '/events/PatchElements.php';
require_once __DIR__ . '/events/PatchSignals.php';
require_once __DIR__ . '/ServerSentEventGenerator.php';
